version: 2
updates:
   - package-ecosystem: "npm"
     directory: "/"
     schedule:
        interval: "daily"
     target-branch: "master"
     allow:
        - dependency-name: "@digiserve/ab-utils"
